name: 'Gitea SARIF to Comment'
description: 'Post SARIF security scan results to Gitea Pull Request comments'
author: 'Hayden Chang'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  sarif-file:
    description: 'Path to the SARIF file'
    required: true
    default: 'scan_results.sarif'
  token:
    description: 'Gitea/GitHub Token'
    required: true
    default: ${{ github.token }}
  title:
    description: 'Title of the comment'
    required: false
    default: '🛡️ Security Scan Results'
  results-limit:
    description: 'Maximum number of results to post'
    required: false
    default: '50'

runs:
  using: 'composite'
  steps:
    - name: Run SARIF Comment Script
      shell: bash
      # Use ${{ github.action_path }} to ensure referencing files within the Action Repo
      run: node "${{ github.action_path }}/sarif-to-comment.mjs"
      env:
        # Pass inputs to environment variables
        INPUT_SARIF_FILE: ${{ inputs.sarif-file }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_RESULTS_LIMIT: ${{ inputs.results-limit }}
        # Variables automatically provided by Gitea Runner
        GITHUB_API_URL: ${{ github.api_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}